### PR TITLE
fix auth

### PR DESCRIPTION
**Pull request by stevemu**

### CODE REVIEW

**Comment by stevemu** [comment]
Please review, then I will do the merge. Thanks!

**Comment by shunsuke218** [comment]
@stevemu It seems that there is a conflict in Navbar.js between auth and dev. Please resolve it first so that I can go ahead and merge?

**Comment by stevemu** [comment]
Yes, I see.

**Comment by stevemu** [comment]
The merge conflict is resolved. Please go ahead and merge into `dev` branch.

**Pull request merged**
